<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\FileManager;
use App\Support\Converters\CharacterConverter;
use App\Support\Converters\NumberConverter;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Brand::create([
            'name' => 'ندارد',
            'latin_name' => 'unknown',
            'escaped_name' => 'ندارد',
            'slug' => str_slug_persian('unknown'),
            'show_in_slider' => false,
            'is_deletable' => false,
        ]);

        if (!app()->isProduction()) {
            /**
             * @var Collection $brandImages
             */
            $brandImages = FileManager::query()->whereLike('full_path', 'brands/', '{value}%')->get();
            $fileBrandMap = [
                'a4tech' => 'a4tech',
                'adata' => 'adata',
                'addlink' => 'addlink',
                'aula' => 'aula',
                'awest' => 'awest',
                'belden' => 'belden',
                'cooler_master' => 'cooler_master',
                'dahua' => 'dahua',
                'deepcool' => 'deepcool',
                'enzo' => 'enzo',
                'intel' => 'intel',
                'lexar' => 'lexar',
                'logitech' => 'logitech',
                'm_s' => 'm_s',
                'microsoft' => 'microsoft',
                'rapoo' => 'rapoo',
                'sandisk' => 'sandisk',
                'seagate' => 'seagate',
                'ebox' => 'ebox',
                'kingmax' => 'kingmax',
                'tp_link' => 'tp_link',
                'tenda' => 'tenda',
            ];

            $sampleBrands = [
                [
                    'name' => 'آئولا',
                    'latin_name' => 'AULA',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('آئولا')),
                    'slug' => str_slug_persian('آئولا'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['aula'])?->id,
                    'keywords' => ['آئولا', 'AULA'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'سن دیسک',
                    'latin_name' => 'sandisk',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('سن دیسک')),
                    'slug' => str_slug_persian('سن دیسک'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['sandisk'])?->id,
                    'keywords' => ['سن دیسک', 'sandisk'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'اینتل',
                    'latin_name' => 'Intel',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('اینتل')),
                    'slug' => str_slug_persian('اینتل'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['intel'])?->id,
                    'keywords' => ['اینتل', 'Intel'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'انزو',
                    'latin_name' => 'ENZO',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('انزو')),
                    'slug' => str_slug_persian('انزو'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['enzo'])?->id,
                    'keywords' => ['انزو', 'ENZO'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'ای فورتک',
                    'latin_name' => 'A4tech',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('ای فورتک')),
                    'slug' => str_slug_persian('ای فورتک'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['a4tech'])?->id,
                    'keywords' => ['ای فورتک', 'A4tech'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'لاجیتک',
                    'latin_name' => 'Logitech',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('لاجیتک')),
                    'slug' => str_slug_persian('لاجیتک'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['logitech'])?->id,
                    'keywords' => ['لاجیتک', 'Logitech'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'اوست',
                    'latin_name' => 'AWEST',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('اوست')),
                    'slug' => str_slug_persian('اوست'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['awest'])?->id,
                    'keywords' => ['اوست', 'AWEST'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'ادلینک',
                    'latin_name' => 'addlink',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('ادلینک')),
                    'slug' => str_slug_persian('ادلینک'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['addlink'])?->id,
                    'keywords' => ['ادلینک', 'addlink'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'ای دیتا',
                    'latin_name' => 'ADATA',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('ای دیتا')),
                    'slug' => str_slug_persian('ای دیتا'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['adata'])?->id,
                    'keywords' => ['ای دیتا', 'ADATA'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'رپو',
                    'latin_name' => 'Rapoo',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('رپو')),
                    'slug' => str_slug_persian('رپو'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['rapoo'])?->id,
                    'keywords' => ['رپو', 'Rapoo'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'ام اند اس',
                    'latin_name' => 'M&S',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('ام اند اس')),
                    'slug' => str_slug_persian('ام اند اس'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['m_s'])?->id,
                    'keywords' => ['ام اند اس', 'M&S'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'دیپ کول',
                    'latin_name' => 'DEEPCOOL',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('دیپ کول')),
                    'slug' => str_slug_persian('دیپ کول'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['deepcool'])?->id,
                    'keywords' => ['دیپ کول', 'DEEPCOOL'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'لکسار',
                    'latin_name' => 'lexar',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('لکسار')),
                    'slug' => str_slug_persian('لکسار'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['lexar'])?->id,
                    'keywords' => ['لکسار', 'lexar'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'کینگ مکس',
                    'latin_name' => 'kingmax',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('کینگ مکس')),
                    'slug' => str_slug_persian('کینگ مکس'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['kingmax'])?->id,
                    'keywords' => ['کینگ مکس', 'kingmax'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'تی پی لینک',
                    'latin_name' => 'tp_link',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('تی پی لینک')),
                    'slug' => str_slug_persian('تی پی لینک'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['tp_link'])?->id,
                    'keywords' => ['تی پی لینک', 'tp_link'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'تندا',
                    'latin_name' => 'Tenda',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('تندا')),
                    'slug' => str_slug_persian('تندا'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['tenda'])?->id,
                    'keywords' => ['تندا', 'Tenda'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'ایباکس',
                    'latin_name' => 'EBOX',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('ایباکس')),
                    'slug' => str_slug_persian('ایباکس'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['ebox'])?->id,
                    'keywords' => ['ایباکس', 'EBOX'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'بلدن',
                    'latin_name' => 'BELDEN',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('بلدن')),
                    'slug' => str_slug_persian('بلدن'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['belden'])?->id,
                    'keywords' => ['بلدن', 'BELDEN'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'داهوا',
                    'latin_name' => 'dahua',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('داهوا')),
                    'slug' => str_slug_persian('داهوا'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['dahua'])?->id,
                    'keywords' => ['داهوا', 'dahua'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'مایکروسافت',
                    'latin_name' => 'Microsoft',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('مایکروسافت')),
                    'slug' => str_slug_persian('مایکروسافت'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['microsoft'])?->id,
                    'keywords' => ['مایکروسافت', 'Microsoft'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'کولر مستر',
                    'latin_name' => 'Cooler Master',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('کولر مستر')),
                    'slug' => str_slug_persian('کولر مستر'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['cooler_master'])?->id,
                    'keywords' => ['کولر مستر', 'Cooler Master'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
                [
                    'name' => 'سیگیت',
                    'latin_name' => 'seagate',
                    'escaped_name' => NumberConverter::toEnglish(CharacterConverter::toPersian('سیگیت')),
                    'slug' => str_slug_persian('سیگیت'),
                    'image_id' => $brandImages->firstWhere('name', $fileBrandMap['seagate'])?->id,
                    'keywords' => ['سیگیت', 'seagate'],
                    'show_in_slider' => true,
                    'is_published' => true,
                    'created_at' => now(),
                ],
            ];

            foreach ($sampleBrands as $brand) {
                Brand::create($brand);
            }
        }
    }
}
