<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Support\Converters\NumberConverter;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sampleCategories = [
            [
                'id' => 2,
                'parent_id' => null,
                'name' => 'موبایل',
                'escaped_name' => 'موبایل',
                'slug' => 'موبایل',
                'ancestry' => null,
                'level' => 0,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 3,
                'parent_id' => 2,
                'name' => 'برندهای مختلف گوشی موبایل',
                'escaped_name' => 'برندهای مختلف گوشی موبایل',
                'slug' => 'برندهای-مختلف-گوشی-موبایل',
                'ancestry' => '2',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 4,
                'parent_id' => 3,
                'name' => 'گوشی آیفون',
                'escaped_name' => 'گوشی آیفون',
                'slug' => 'گوشی-آیفون',
                'ancestry' => '3|2',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 5,
                'parent_id' => null,
                'name' => 'کالای دیجیتال',
                'escaped_name' => 'کالای دیجیتال',
                'slug' => 'کالای-دیجیتال',
                'ancestry' => null,
                'level' => 0,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'name' => 'خانه و آشپزخانه',
                'escaped_name' => 'خانه و آشپزخانه',
                'slug' => 'خانه-و-آشپزخانه',
                'ancestry' => null,
                'level' => 0,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 7,
                'parent_id' => null,
                'name' => 'لوازم خانگی برقی',
                'escaped_name' => 'لوازم خانگی برقی',
                'slug' => 'لوازم-خانگی-برقی',
                'ancestry' => null,
                'level' => 0,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 8,
                'parent_id' => null,
                'name' => 'مد و پوشاک',
                'escaped_name' => 'مد و پوشاک',
                'slug' => 'مد-و-پوشاک',
                'ancestry' => null,
                'level' => 0,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 9,
                'parent_id' => null,
                'name' => 'زیبایی و سلامت',
                'escaped_name' => 'زیبایی و سلامت',
                'slug' => 'زیبایی-و-سلامت',
                'ancestry' => null,
                'level' => 0,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 10,
                'parent_id' => 3,
                'name' => 'گوشی سامسونگ',
                'escaped_name' => 'گوشی سامسونگ',
                'slug' => 'گوشی-سامسونگ',
                'ancestry' => '3|2',
                'level' => 2,
                'priority' => 1,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 11,
                'parent_id' => 3,
                'name' => 'گوشی شیائومی',
                'escaped_name' => 'گوشی شیائومی',
                'slug' => 'گوشی-شیائومی',
                'ancestry' => '3|2',
                'level' => 2,
                'priority' => 2,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 12,
                'parent_id' => 2,
                'name' => 'گوشی بر اساس قیمت',
                'escaped_name' => 'گوشی بر اساس قیمت',
                'slug' => 'گوشی-بر-اساس-قیمت',
                'ancestry' => '2',
                'level' => 1,
                'priority' => 1,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 13,
                'parent_id' => 2,
                'name' => 'گوشی بر اساس عملکرد',
                'escaped_name' => 'گوشی بر اساس عملکرد',
                'slug' => 'گوشی-بر-اساس-عملکرد',
                'ancestry' => '2',
                'level' => 1,
                'priority' => 2,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 14,
                'parent_id' => 2,
                'name' => 'لوازم جانبی موبایل',
                'escaped_name' => 'لوازم جانبی موبایل',
                'slug' => 'لوازم-جانبی-موبایل',
                'ancestry' => '2',
                'level' => 1,
                'priority' => 3,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 15,
                'parent_id' => 2,
                'name' => 'تبلت',
                'escaped_name' => 'تبلت',
                'slug' => 'تبلت',
                'ancestry' => '2',
                'level' => 1,
                'priority' => 4,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 16,
                'parent_id' => 12,
                'name' => 'گوشی موبایل ارزان',
                'escaped_name' => 'گوشی موبایل ارزان',
                'slug' => 'گوشی-موبایل-ارزان',
                'ancestry' => '12|2',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 17,
                'parent_id' => 12,
                'name' => 'گوشی موبایل قسطی',
                'escaped_name' => 'گوشی موبایل قسطی',
                'slug' => 'گوشی-موبایل-قسطی',
                'ancestry' => '12|2',
                'level' => 2,
                'priority' => 1,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 18,
                'parent_id' => 12,
                'name' => 'گوشی تا 2 میلیون تومان',
                'escaped_name' => 'گوشی تا 2 میلیون تومان',
                'slug' => 'گوشی-تا-2-میلیون-تومان',
                'ancestry' => '12|2',
                'level' => 2,
                'priority' => 2,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 19,
                'parent_id' => 12,
                'name' => 'گوشی تا 5 میلیون تومان',
                'escaped_name' => 'گوشی تا 5 میلیون تومان',
                'slug' => 'گوشی-تا-5-میلیون-تومان',
                'ancestry' => '12|2',
                'level' => 2,
                'priority' => 3,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 20,
                'parent_id' => 13,
                'name' => 'گوشی گیمینگ',
                'escaped_name' => 'گوشی گیمینگ',
                'slug' => 'گوشی-گیمینگ',
                'ancestry' => '13|2',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 21,
                'parent_id' => 13,
                'name' => 'گوشی 5g',
                'escaped_name' => 'گوشی 5g',
                'slug' => 'گوشی-5g',
                'ancestry' => '13|2',
                'level' => 2,
                'priority' => 1,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 22,
                'parent_id' => 13,
                'name' => 'گوشی دکمه‌ای',
                'escaped_name' => 'گوشی دکمه‌ای',
                'slug' => 'گوشی-دکمه-ای',
                'ancestry' => '13|2',
                'level' => 2,
                'priority' => 2,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 23,
                'parent_id' => 14,
                'name' => 'شارژر گوشی',
                'escaped_name' => 'شارژر گوشی',
                'slug' => 'شارژر-گوشی',
                'ancestry' => '14|2',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 24,
                'parent_id' => 14,
                'name' => 'قاب و کاور گوشی',
                'escaped_name' => 'قاب و کاور گوشی',
                'slug' => 'قاب-و-کاور-گوشی',
                'ancestry' => '14|2',
                'level' => 2,
                'priority' => 1,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 25,
                'parent_id' => 14,
                'name' => 'گلس گوشی',
                'escaped_name' => 'گلس گوشی',
                'slug' => 'گلس-گوشی',
                'ancestry' => '14|2',
                'level' => 2,
                'priority' => 2,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 26,
                'parent_id' => 14,
                'name' => 'هولدر گوشی موبایل',
                'escaped_name' => 'هولدر گوشی موبایل',
                'slug' => 'هولدر-گوشی-موبایل',
                'ancestry' => '14|2',
                'level' => 2,
                'priority' => 3,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 27,
                'parent_id' => 15,
                'name' => 'تبلت سامسونگ',
                'escaped_name' => 'تبلت سامسونگ',
                'slug' => 'تبلت-سامسونگ',
                'ancestry' => '15|2',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 28,
                'parent_id' => 15,
                'name' => 'تبلت اپل (آی پد)',
                'escaped_name' => 'تبلت اپل (آی پد)',
                'slug' => 'تبلت-اپل-آی-پد',
                'ancestry' => '15|2',
                'level' => 2,
                'priority' => 1,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 29,
                'parent_id' => 15,
                'name' => 'تبلت شیائومی',
                'escaped_name' => 'تبلت شیائومی',
                'slug' => 'تبلت-شیائومی',
                'ancestry' => '15|2',
                'level' => 2,
                'priority' => 2,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 30,
                'parent_id' => 2,
                'name' => 'هدفون',
                'escaped_name' => 'هدفون',
                'slug' => 'هدفون',
                'ancestry' => '2',
                'level' => 1,
                'priority' => 5,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 31,
                'parent_id' => 30,
                'name' => 'هدفون بیسیم',
                'escaped_name' => 'هدفون بیسیم',
                'slug' => 'هدفون-بیسیم',
                'ancestry' => '30|2',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 32,
                'parent_id' => 30,
                'name' => 'هدفون اپل (ایرپاد)',
                'escaped_name' => 'هدفون اپل (ایرپاد)',
                'slug' => 'هدفون-اپل-ایرپاد',
                'ancestry' => '30|2',
                'level' => 2,
                'priority' => 1,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 33,
                'parent_id' => 30,
                'name' => 'هدفون بیتس',
                'escaped_name' => 'هدفون بیتس',
                'slug' => 'هدفون-بیتس',
                'ancestry' => '30|2',
                'level' => 2,
                'priority' => 1,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 34,
                'parent_id' => null,
                'name' => 'کامپیوتر و تجهیزات جانبی',
                'escaped_name' => NumberConverter::toEnglish('کامپیوتر و تجهیزات جانبی'),
                'slug' => str_slug_persian('کامپیوتر و تجهیزات جانبی'),
                'ancestry' => null,
                'level' => 0,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 35,
                'parent_id' => null,
                'name' => 'تجهیزات ذخیره‌سازی اطلاعات',
                'escaped_name' => NumberConverter::toEnglish('تجهیزات ذخیره‌سازی اطلاعات'),
                'slug' => str_slug_persian('تجهیزات ذخیره‌سازی اطلاعات'),
                'ancestry' => null,
                'level' => 0,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 36,
                'parent_id' => null,
                'name' => 'مودم و تجهیزات شبکه',
                'escaped_name' => NumberConverter::toEnglish('مودم و تجهیزات شبکه'),
                'slug' => str_slug_persian('مودم و تجهیزات شبکه'),
                'ancestry' => null,
                'level' => 0,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 37,
                'parent_id' => 34,
                'name' => 'کیبورد و ماوس پد',
                'escaped_name' => NumberConverter::toEnglish('کیبورد و ماوس پد'),
                'slug' => str_slug_persian('کیبورد و ماوس پد'),
                'ancestry' => '34',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 38,
                'parent_id' => 34,
                'name' => 'ماوس',
                'escaped_name' => NumberConverter::toEnglish('ماوس'),
                'slug' => str_slug_persian('ماوس'),
                'ancestry' => '34',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 39,
                'parent_id' => 34,
                'name' => 'خنک کننده کامپیوتر',
                'escaped_name' => NumberConverter::toEnglish('خنک کننده کامپیوتر'),
                'slug' => str_slug_persian('خنک کننده کامپیوتر'),
                'ancestry' => '34',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 40,
                'parent_id' => 39,
                'name' => 'خنک کننده پردازنده',
                'escaped_name' => NumberConverter::toEnglish('خنک کننده پردازنده'),
                'slug' => str_slug_persian('خنک کننده پردازنده'),
                'ancestry' => '39|34',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 41,
                'parent_id' => 39,
                'name' => 'خنک کننده کیس',
                'escaped_name' => NumberConverter::toEnglish('خنک کننده کیس'),
                'slug' => str_slug_persian('خنک کننده کیس'),
                'ancestry' => '39|34',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 42,
                'parent_id' => 34,
                'name' => 'براکت هارد',
                'escaped_name' => NumberConverter::toEnglish('براکت هارد'),
                'slug' => str_slug_persian('براکت هارد'),
                'ancestry' => '34',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 43,
                'parent_id' => 34,
                'name' => 'قطعات داخلی کامپیوتر',
                'escaped_name' => NumberConverter::toEnglish('قطعات داخلی کامپیوتر'),
                'slug' => str_slug_persian('قطعات داخلی کامپیوتر'),
                'ancestry' => '34',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 44,
                'parent_id' => 42,
                'name' => 'رم کامپیوتر و لپ‌تاپ (RAM)',
                'escaped_name' => NumberConverter::toEnglish('رم کامپیوتر و لپ‌تاپ (RAM)'),
                'slug' => str_slug_persian('رم کامپیوتر و لپ‌تاپ (RAM)'),
                'ancestry' => '42|34',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 45,
                'parent_id' => 42,
                'name' => 'منبع تغذیه کامپیوتر',
                'escaped_name' => NumberConverter::toEnglish('منبع تغذیه کامپیوتر'),
                'slug' => str_slug_persian('منبع تغذیه کامپیوتر'),
                'ancestry' => '42|34',
                'level' => 2,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 46,
                'parent_id' => 34,
                'name' => 'کیبورد',
                'escaped_name' => NumberConverter::toEnglish('کیبورد'),
                'slug' => str_slug_persian('کیبورد'),
                'ancestry' => '34',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 47,
                'parent_id' => 34,
                'name' => 'انواع کابل و مبدل ها',
                'escaped_name' => NumberConverter::toEnglish('انواع کابل و مبدل ها'),
                'slug' => str_slug_persian('انواع کابل و مبدل ها'),
                'ancestry' => '34',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 48,
                'parent_id' => 35,
                'name' => 'لوازم جانبی تجهیزات ذخیره سازی',
                'escaped_name' => NumberConverter::toEnglish('لوازم جانبی تجهیزات ذخیره سازی'),
                'slug' => str_slug_persian('لوازم جانبی تجهیزات ذخیره سازی'),
                'ancestry' => '35',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 49,
                'parent_id' => 35,
                'name' => 'سوییچ',
                'escaped_name' => NumberConverter::toEnglish('سوییچ'),
                'slug' => str_slug_persian('سوییچ'),
                'ancestry' => '35',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 50,
                'parent_id' => 35,
                'name' => 'کارت شبکه',
                'escaped_name' => NumberConverter::toEnglish('کارت شبکه'),
                'slug' => str_slug_persian('کارت شبکه'),
                'ancestry' => '35',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 51,
                'parent_id' => 35,
                'name' => 'حافظه SSD',
                'escaped_name' => NumberConverter::toEnglish('حافظه SSD'),
                'slug' => str_slug_persian('حافظه SSD'),
                'ancestry' => '35',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 52,
                'parent_id' => 35,
                'name' => 'فلش مموری',
                'escaped_name' => NumberConverter::toEnglish('فلش مموری'),
                'slug' => str_slug_persian('فلش مموری'),
                'ancestry' => '35',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 53,
                'parent_id' => 35,
                'name' => 'هارد دیسک اکسترنال',
                'escaped_name' => NumberConverter::toEnglish('هارد دیسک اکسترنال'),
                'slug' => str_slug_persian('هارد دیسک اکسترنال'),
                'ancestry' => '35',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 54,
                'parent_id' => 36,
                'name' => 'کابل شبکه (LAN)',
                'escaped_name' => NumberConverter::toEnglish('کابل شبکه (LAN)'),
                'slug' => str_slug_persian('کابل شبکه (LAN)'),
                'ancestry' => '36',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
            [
                'id' => 55,
                'parent_id' => 36,
                'name' => 'آداپتور مودم',
                'escaped_name' => NumberConverter::toEnglish('آداپتور مودم'),
                'slug' => str_slug_persian('آداپتور مودم'),
                'ancestry' => '36',
                'level' => 1,
                'priority' => 0,
                'show_in_menu' => 1,
                'show_in_search_side_menu' => 1,
                'show_in_slider' => 1,
                'is_published' => 1,
                'is_deletable' => 1,
            ],
        ];

        Category::create(['name' => 'بدون دسته‌بندی',
            'escaped_name' => 'بدون دسته‌بندی',
            'slug' => str_slug_persian('بدون دسته‌بندی'),
            'show_in_menu' => false,
            'show_in_search_side_menu' => false,
            'show_in_slider' => false,
            'is_deletable' => false,
        ]);

        foreach ($sampleCategories as $category) {
            Category::create($category);
        }
    }
}
