<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    private array $sampleCategories = [
        [
            'parent_id' => null,
            'name' => 'موبایل',
            'escaped_name' => 'موبایل',
            'slug' => 'موبایل',
            'ancestry' => null,
            'level' => 0,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 2,
            'name' => 'برندهای مختلف گوشی موبایل',
            'escaped_name' => 'برندهای مختلف گوشی موبایل',
            'slug' => 'برندهای-مختلف-گوشی-موبایل',
            'ancestry' => '2',
            'level' => 1,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 3,
            'name' => 'گوشی آیفون',
            'escaped_name' => 'گوشی آیفون',
            'slug' => 'گوشی-آیفون',
            'ancestry' => '3|2',
            'level' => 2,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => null,
            'name' => 'کالای دیجیتال',
            'escaped_name' => 'کالای دیجیتال',
            'slug' => 'کالای-دیجیتال',
            'ancestry' => null,
            'level' => 0,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => null,
            'name' => 'خانه و آشپزخانه',
            'escaped_name' => 'خانه و آشپزخانه',
            'slug' => 'خانه-و-آشپزخانه',
            'ancestry' => null,
            'level' => 0,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => null,
            'name' => 'لوازم خانگی برقی',
            'escaped_name' => 'لوازم خانگی برقی',
            'slug' => 'لوازم-خانگی-برقی',
            'ancestry' => null,
            'level' => 0,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => null,
            'name' => 'مد و پوشاک',
            'escaped_name' => 'مد و پوشاک',
            'slug' => 'مد-و-پوشاک',
            'ancestry' => null,
            'level' => 0,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => null,
            'name' => 'زیبایی و سلامت',
            'escaped_name' => 'زیبایی و سلامت',
            'slug' => 'زیبایی-و-سلامت',
            'ancestry' => null,
            'level' => 0,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 3,
            'name' => 'گوشی سامسونگ',
            'escaped_name' => 'گوشی سامسونگ',
            'slug' => 'گوشی-سامسونگ',
            'ancestry' => '3|2',
            'level' => 2,
            'priority' => 1,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 3,
            'name' => 'گوشی شیائومی',
            'escaped_name' => 'گوشی شیائومی',
            'slug' => 'گوشی-شیائومی',
            'ancestry' => '3|2',
            'level' => 2,
            'priority' => 2,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 2,
            'name' => 'گوشی بر اساس قیمت',
            'escaped_name' => 'گوشی بر اساس قیمت',
            'slug' => 'گوشی-بر-اساس-قیمت',
            'ancestry' => '2',
            'level' => 1,
            'priority' => 1,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 2,
            'name' => 'گوشی بر اساس عملکرد',
            'escaped_name' => 'گوشی بر اساس عملکرد',
            'slug' => 'گوشی-بر-اساس-عملکرد',
            'ancestry' => '2',
            'level' => 1,
            'priority' => 2,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 2,
            'name' => 'لوازم جانبی موبایل',
            'escaped_name' => 'لوازم جانبی موبایل',
            'slug' => 'لوازم-جانبی-موبایل',
            'ancestry' => '2',
            'level' => 1,
            'priority' => 3,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 2,
            'name' => 'تبلت',
            'escaped_name' => 'تبلت',
            'slug' => 'تبلت',
            'ancestry' => '2',
            'level' => 1,
            'priority' => 4,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 12,
            'name' => 'گوشی موبایل ارزان',
            'escaped_name' => 'گوشی موبایل ارزان',
            'slug' => 'گوشی-موبایل-ارزان',
            'ancestry' => '12|2',
            'level' => 2,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 12,
            'name' => 'گوشی موبایل قسطی',
            'escaped_name' => 'گوشی موبایل قسطی',
            'slug' => 'گوشی-موبایل-قسطی',
            'ancestry' => '12|2',
            'level' => 2,
            'priority' => 1,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 12,
            'name' => 'گوشی تا 2 میلیون تومان',
            'escaped_name' => 'گوشی تا 2 میلیون تومان',
            'slug' => 'گوشی-تا-2-میلیون-تومان',
            'ancestry' => '12|2',
            'level' => 2,
            'priority' => 2,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 12,
            'name' => 'گوشی تا 5 میلیون تومان',
            'escaped_name' => 'گوشی تا 5 میلیون تومان',
            'slug' => 'گوشی-تا-5-میلیون-تومان',
            'ancestry' => '12|2',
            'level' => 2,
            'priority' => 3,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 13,
            'name' => 'گوشی گیمینگ',
            'escaped_name' => 'گوشی گیمینگ',
            'slug' => 'گوشی-گیمینگ',
            'ancestry' => '13|2',
            'level' => 2,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 13,
            'name' => 'گوشی 5g',
            'escaped_name' => 'گوشی 5g',
            'slug' => 'گوشی-5g',
            'ancestry' => '13|2',
            'level' => 2,
            'priority' => 1,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 13,
            'name' => 'گوشی دکمه‌ای',
            'escaped_name' => 'گوشی دکمه‌ای',
            'slug' => 'گوشی-دکمه-ای',
            'ancestry' => '13|2',
            'level' => 2,
            'priority' => 2,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 14,
            'name' => 'شارژر گوشی',
            'escaped_name' => 'شارژر گوشی',
            'slug' => 'شارژر-گوشی',
            'ancestry' => '14|2',
            'level' => 2,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 14,
            'name' => 'قاب و کاور گوشی',
            'escaped_name' => 'قاب و کاور گوشی',
            'slug' => 'قاب-و-کاور-گوشی',
            'ancestry' => '14|2',
            'level' => 2,
            'priority' => 1,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 14,
            'name' => 'گلس گوشی',
            'escaped_name' => 'گلس گوشی',
            'slug' => 'گلس-گوشی',
            'ancestry' => '14|2',
            'level' => 2,
            'priority' => 2,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 14,
            'name' => 'هولدر گوشی موبایل',
            'escaped_name' => 'هولدر گوشی موبایل',
            'slug' => 'هولدر-گوشی-موبایل',
            'ancestry' => '14|2',
            'level' => 2,
            'priority' => 3,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 15,
            'name' => 'تبلت سامسونگ',
            'escaped_name' => 'تبلت سامسونگ',
            'slug' => 'تبلت-سامسونگ',
            'ancestry' => '15|2',
            'level' => 2,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 15,
            'name' => 'تبلت اپل (آی پد)',
            'escaped_name' => 'تبلت اپل (آی پد)',
            'slug' => 'تبلت-اپل-آی-پد',
            'ancestry' => '15|2',
            'level' => 2,
            'priority' => 1,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 15,
            'name' => 'تبلت شیائومی',
            'escaped_name' => 'تبلت شیائومی',
            'slug' => 'تبلت-شیائومی',
            'ancestry' => '15|2',
            'level' => 2,
            'priority' => 2,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 2,
            'name' => 'هدفون',
            'escaped_name' => 'هدفون',
            'slug' => 'هدفون',
            'ancestry' => '2',
            'level' => 1,
            'priority' => 5,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 30,
            'name' => 'هدفون بیسیم',
            'escaped_name' => 'هدفون بیسیم',
            'slug' => 'هدفون-بیسیم',
            'ancestry' => '30|2',
            'level' => 2,
            'priority' => 0,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 30,
            'name' => 'هدفون اپل (ایرپاد)',
            'escaped_name' => 'هدفون اپل (ایرپاد)',
            'slug' => 'هدفون-اپل-ایرپاد',
            'ancestry' => '30|2',
            'level' => 2,
            'priority' => 1,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
        [
            'parent_id' => 30,
            'name' => 'هدفون بیتس',
            'escaped_name' => 'هدفون بیتس',
            'slug' => 'هدفون-بیتس',
            'ancestry' => '30|2',
            'level' => 2,
            'priority' => 1,
            'show_in_menu' => 1,
            'show_in_search_side_menu' => 1,
            'show_in_slider' => 1,
            'is_published' => 1,
            'is_deletable' => 1,
        ],
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Category::create(['name' => 'بدون دسته‌بندی',
            'escaped_name' => 'بدون دسته‌بندی',
            'slug' => str_slug_persian('بدون دسته‌بندی'),
            'show_in_menu' => false,
            'show_in_search_side_menu' => false,
            'show_in_slider' => false,
            'is_deletable' => false,
        ]);

        foreach ($this->sampleCategories as $category) {
            Category::create($category);
        }
    }
}
