<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $productionSeeders = [
            ProvinceAndCitySeeder::class,
            RolesAndPermissionsSeeder::class,
            UserSeeder::class,
            //
            SettingSeeder::class,
            //
            PaymentMethodSeeder::class,
            //
            BlogCommentBadgeSeeder::class,
            //
            PageSeeder::class,
            //
            MenuAndPlaceSeeder::class,
            SliderSeeder::class,
            //
            ColorSeeder::class,
            BrandSeeder::class,
            UnitSeeder::class,
            //
            OrderBadgeSeeder::class,
        ];
        $otherSeeders = [
            FileManagerSeeder::class,
            //
            UserAutogeneratedSeeder::class,
            //
            SendMethodSeeder::class,
            //
            BlogSeeder::class,
            BlogCommentSeeder::class,
            //
            CategorySeeder::class,
            ProductSeeder::class,
            ProductCommentSeeder::class,
        ];

        $seeders = app()->isProduction()
            ? $productionSeeders
            : array_merge($productionSeeders, $otherSeeders);
        $this->call($seeders);
    }
}
