<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Color;
use App\Models\FileManager;
use App\Models\Product;
use App\Models\ProductProperty;
use App\Support\Converters\NumberConverter;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mappedImages = [
            'AULA' => 'aula',
            'sandisk' => 'sandisk',
            'Intel' => 'intel',
            'ENZO' => 'enzo',
            'A4tech' => 'a4tech',
            'Logitech' => 'logitech',
            'AWEST' => 'awest',
            'addlink' => 'addlink',
            'ADATA' => 'adata',
            'Rapoo' => 'rapoo',
            'M&S' => 'm_s',
            'DEEPCOOL' => 'deepcool',
            'lexar' => 'lexar',
            'kingmax' => 'kingmax',
            'tp_link' => 'tp_link',
            'Tenda' => 'tenda',
            'EBOX' => 'ebox',
            'BELDEN' => 'belden',
            'dahua' => 'dahua',
            'Microsoft' => 'microsoft',
            'Cooler Master' => 'cooler_master',
            'seagate' => 'seagate',
        ];
        $colors = Color::all();
        $products = [
            [
                'title' => 'ماوس پد آئولا مدل AULA MP-W',
                'brand' => 'AULA',
                'category' => 'کیبورد و ماوس پد',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"ماوس پد آئولا مدل AULA MP-W',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'اصالت و سلامت فیزیکی',
                    'weight' => 50,
                    'price' => 37900,
                    'stock_count' => 466,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 27490,
                ],
            ],
            [
                'title' => 'فلش مموری USB 3.0 سن دیسک مدل SanDisk Ultra Flair CZ73 32GB',
                'brand' => 'sandisk',
                'category' => 'فلش مموری',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"فلش مموری سن دیسک',
                    'فلش مموری',
                    'فلش مموری سن دیسک مدل Ultra Flair CZ73',
                    'Ultra Flair CZ73 ظرفیت 32 گیگابایت',
                    ' سن دیسک',
                    '32 گیگابایت',
                    'USB',
                    'فلش مموری USB 3.0 سن دیسک مدل SanDisk Ultra Flair CZ73 32GB',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'نقره ای',
                    'size' => null,
                    'guarantee' => 'سازگار',
                    'weight' => 2,
                    'price' => 250000,
                    'stock_count' => 251,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 234900,
                ],
            ],
            [
                'title' => 'ماوس با سیم آئولا مدل AULA AM104',
                'brand' => 'AULA',
                'category' => 'ماوس',
                'unit_name' => 'عدد',
                'keywords' => [
                    'ماوس با سیم آئولا مدل AULA AM104',
                    'نمایندگی انزو سرویس',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'گارانتی : انزو سرویس',
                    'نمایندگی انزو',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'انزو سرویس',
                    'weight' => 500,
                    'price' => 124000,
                    'stock_count' => 244,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 119000,
                ],
            ],
            [
                'title' => 'خنک کننده پردازنده اورجینال اینتل مدل INTEL Core i3-10105F',
                'brand' => 'Intel',
                'category' => 'خنک کننده پردازنده',
                'unit_name' => 'عدد',
                'keywords' => [
                    'گارانتی : اصالت و سلامت فیزیکی کالا',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'خنک کننده پردازنده اورجینال اینتل مدل INTEL Core i3-10105F',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'اصالت و سلامت فیزیکی کالا',
                    'weight' => 300,
                    'price' => 330000,
                    'stock_count' => 165,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 299000,
                ],
            ],
            [
                'title' => 'براکت هارد اینترنال انزو ENZO HDD/SSD Caddy EB-91 12.7MM',
                'brand' => 'ENZO',
                'category' => 'براکت هارد',
                'unit_name' => 'عدد',
                'keywords' => [
                    'گارانتی : انزو سرویس',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'براکت هارد اینترنال انزو ENZO HDD/SSD Caddy EB-91 12.7MM',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'نقره ای',
                    'size' => null,
                    'guarantee' => 'انزو سرویس',
                    'weight' => 200,
                    'price' => 120000,
                    'stock_count' => 130,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 99000,
                ],
            ],
            [
                'title' => 'براکت هارد اینترنال انزو ENZO HDD/SSD Caddy EB-90 9.5MM',
                'brand' => 'ENZO',
                'category' => 'براکت هارد',
                'unit_name' => 'عدد',
                'keywords' => [
                    'گارانتی : انزو سرویس',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'براکت هارد اینترنال انزو ENZO HDD/SSD Caddy EB-90 9.5MM',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'نقره ای',
                    'size' => null,
                    'guarantee' => 'انزو سرویس',
                    'weight' => 200,
                    'price' => 120000,
                    'stock_count' => 130,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 99000,
                ],
            ],
            [
                'title' => 'ماوس پد طبی طرح ای فورتک مدل A4TECH PD700',
                'brand' => 'A4tech',
                'category' => 'کیبورد و ماوس پد',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"ماوس پد طبی طرح ای فورتک مدل A4TECH PD 700',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'سلامت فیزیکی',
                    'weight' => 400,
                    'price' => 158000,
                    'stock_count' => 114,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 150000,
                ],
            ],
            [
                'title' => 'ماوس پد طبی طرح لاجیتک مدل Logitech PD600',
                'brand' => 'Logitech',
                'category' => 'کیبورد و ماوس پد',
                'unit_name' => 'عدد',
                'keywords' => [
                    'گارانتی : سلامت فیزیکی',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'ماوس پد طبی طرح لاجیتک مدل Logitech PD 600',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'سلامت فیزیکی',
                    'weight' => 500,
                    'price' => 88000,
                    'stock_count' => 111,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                ],
            ],
            [
                'title' => 'خنک کننده پردازنده اوست مدل AWEST GT-AV90 OMEGA COOL',
                'brand' => 'AWEST',
                'category' => 'خنک کننده پردازنده',
                'unit_name' => 'عدد',
                'keywords' => [
                    'گارانتی : 12 ماهه تابا',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'خنک کننده پردازنده اوست مدل AWEST GT-AV90 OMEGA COOL',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'نقره ای',
                    'size' => null,
                    'guarantee' => 'تابا',
                    'weight' => 220,
                    'price' => 490000,
                    'stock_count' => 107,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 409000,
                ],
            ],
            [
                'title' => 'خنک کننده پردازنده اینتل مدل INTEL Core i5-12400 LGA-1700',
                'brand' => 'Intel',
                'category' => 'خنک کننده پردازنده',
                'unit_name' => 'عدد',
                'keywords' => [
                    'گارانتی : اصالت و سلامت فیزیکی',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'خنک کننده پردازنده اینتل مدل INTEL Core i5-12400 LGA-1700',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'نقره ای',
                    'size' => null,
                    'guarantee' => 'اصالت و سلامت فیزیکی',
                    'weight' => 400,
                    'price' => 590000,
                    'stock_count' => 104,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 499000,
                ],
            ],
            [
                'title' => 'فلش Type-C OTG سن دیسک مدل SanDisk Ultra Dual Drive Go 32GB',
                'brand' => 'sandisk',
                'category' => 'فلش مموری',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"فلش Type-C OTG سن دیسک مدل SanDisk Ultra Dual Drive Go 32GB',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'مادام العمر سازگار',
                    'weight' => 300,
                    'price' => 355000,
                    'stock_count' => 88,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 322990,
                ],
            ],
            [
                'title' => 'اس اس دی اینترنال ادلینک مدل AddLink S20 512GB',
                'brand' => 'addlink',
                'category' => 'حافظه SSD',
                'unit_name' => 'عدد',
                'keywords' => [
                    'اس اس دی',
                    'SSD',
                    'pars gostar',
                    'پارس گستر',
                    'خرید انلاین',
                    'اس اس دی اینترنال ادلینک مدل AddLink S20 512GB',
                    'گارانتی : آواژنگ',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'آواژنگ',
                    'weight' => 100,
                    'price' => 2150000,
                    'stock_count' => 84,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 1929000,
                ],
            ],
            [
                'title' => 'فلش مموری USB 3.2 ای دیتا مدل ADATA UV150 32GB',
                'brand' => 'ADATA',
                'category' => 'فلش مموری',
                'unit_name' => 'عدد',
                'keywords' => [
                    'پارس گستر',
                    'خرید آنلاین',
                    'فروشگاه آنلاین',
                    'ای دیتا',
                    'گارانتی : آونگ',
                    'نمایندگی آونگ',
                    'ADATA',
                    'AVANG',
                    'PARS GOSTAR',
                    'فلش مموری USB 3.2 ای دیتا مدل ADATA UV150 32GB',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => '36 ماهه آونگ',
                    'weight' => 50,
                    'price' => 300000,
                    'stock_count' => 81,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 211900,
                ],
            ],
            [
                'title' => 'آداپتور مودم انزو مدل ENZO B-2091 9V 1A',
                'brand' => 'ENZO',
                'category' => 'آداپتور مودم',
                'unit_name' => 'عدد',
                'keywords' => [
                    'آداپتور مودم انزو مدل ENZO B-2091 9V 1A',
                    'گارانتی : انزو ',
                    'نمایندگی انزو ',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'انزو سرویس',
                    'weight' => 200,
                    'price' => 75000,
                    'stock_count' => 76,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 64900,
                ],
            ],
            [
                'title' => 'ماوس رپو مدل RAPOO N200',
                'brand' => 'Rapoo',
                'category' => 'ماوس',
                'unit_name' => 'عدد',
                'keywords' => [
                    'پارس گستر',
                    'ماوس رپو مدل RAPOO N200',
                    'خرید آنلاین',
                    'فروشگاه آنلاین',
                    'گارانتی : پانا',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'پانا',
                    'weight' => 45,
                    'price' => 170000,
                    'stock_count' => 75,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 152000,
                ],
            ],
            [
                'title' => 'کیف هارد دیسک اکسترنال M&S سایز کوچک',
                'brand' => 'M&S',
                'category' => 'لوازم جانبی تجهیزات ذخیره سازی',
                'unit_name' => 'عدد',
                'keywords' => [
                    'کیف هارد دیسک اکسترنال M&S سایز گوچک',
                    'گارانتی : اصالت و سلامت فیزیکی',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'اصالت و سلامت فیزیکی کالا',
                    'weight' => 400,
                    'price' => 135000,
                    'stock_count' => 71,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 119000,
                ],
            ],
            [
                'title' => 'ماوس بی سیم رپو مدل RAPOO M216',
                'brand' => 'Rapoo',
                'category' => 'ماوس',
                'unit_name' => 'عدد',
                'keywords' => [
                    'ماوس بی سیم رپو مدل RAPOO M216',
                    'گارانتی : پانا',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'نمایندگی rapoo',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'پانا',
                    'weight' => 100,
                    'price' => 320000,
                    'stock_count' => 70,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 283900,
                ],
            ],
            [
                'title' => 'خنک کننده پردازنده دیپ کول DEEPCOOL ALTA 9 PWM LGA1700',
                'brand' => 'DEEPCOOL',
                'category' => 'خنک کننده پردازنده',
                'unit_name' => 'عدد',
                'keywords' => [
                    'خنک کننده پردازنده دیپ کول DEEPCOOL ALTA 9 PWM LGA1700',
                    'نمایندگی دیپ کول',
                    'نمایندگی فراسیستم',
                    'گارانتی : فراسیستم',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'فاقد مولفه رنگ',
                    'size' => null,
                    'guarantee' => 'فراسیستم',
                    'weight' => 500,
                    'price' => 560000,
                    'stock_count' => 68,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 509000,
                ],
            ],
            [
                'title' => 'رم دسکتاپ لکسار مدل Lexar LD4AU008G 8GB DDR4-3200 CL22',
                'brand' => 'lexar',
                'category' => 'رم کامپیوتر و لپ‌تاپ (RAM)',
                'unit_name' => 'عدد',
                'keywords' => [
                    'رم دسکتاپ لکسار مدل Lexar LD4AU008G 8GB DDR4-3200 CL22',
                    'گارانتی : حامی',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'حامی',
                    'weight' => 300,
                    'price' => 880000,
                    'stock_count' => 60,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 799000,
                ],
            ],
            [
                'title' => 'اس اس دی ای دیتا مدل ADATA SU630 240GB',
                'brand' => 'ADATA',
                'category' => 'حافظه SSD',
                'unit_name' => 'عدد',
                'keywords' => [
                    'خرید آنلاین',
                    'فروشگاه آنلاین',
                    'پارس گستر',
                    'ای دیتا',
                    'گارانتی : آونگ',
                    'نمایندگی آونگ',
                    'ADATA',
                    'PARSGOSTAR',
                    'اس اس دی ای دیتا مدل ADATA Ultimate SU630 240GB',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => '36 ماهه آونگ',
                    'weight' => 200,
                    'price' => 1489000,
                    'stock_count' => 57,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 1259000,
                ],
            ],
            [
                'title' => 'فلش مموری USB 3.2 ای دیتا مدل ADATA UR340 64GB',
                'brand' => 'ADATA',
                'category' => 'فلش مموری',
                'unit_name' => 'عدد',
                'keywords' => [
                    'فلش مموری USB 3.2 ای دیتا مدل ADATA UR340 64GB',
                    'نمایندگی ای دیتا',
                    'نمایندگی آونگ',
                    'خرید انلاین',
                    'پارس گستر',
                    'فروشگاه انلاین',
                    'PARS GOSTAR',
                    'گارانتی : 60 ماهه آونگ',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => '60 ماهه آونگ',
                    'weight' => 400,
                    'price' => 350000,
                    'stock_count' => 55,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 317890,
                ],
            ],
            [
                'title' => 'اس اس دی اینترنال کینگ مکس مدل KingMax KM240GSMV32 240GB',
                'brand' => 'kingmax',
                'category' => 'حافظه SSD',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"اس اس دی اینترنال کینگ مکس مدل KingMax KM240GSMV32 240GB',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'آواژنگ',
                    'weight' => 200,
                    'price' => 1290000,
                    'stock_count' => 54,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 1149000,
                ],
            ],
            [
                'title' => 'رم دسکتاپ کینگ مکس مدل Kingmax 8GB DDR4-3200MHz',
                'brand' => 'kingmax',
                'category' => 'رم کامپیوتر و لپ‌تاپ (RAM)',
                'unit_name' => 'عدد',
                'keywords' => [
                    'گارانتی : مادام العمر آواژنگ',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'PARS GOSTAR',
                    'رم دسکتاپ کینگ مکس مدل Kingmax 8GB DDR4-3200MHz',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'تک رنگ',
                    'size' => null,
                    'guarantee' => 'مادام العمر آواژنگ',
                    'weight' => 80,
                    'price' => 995000,
                    'stock_count' => 52,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 929000,
                ],
            ],
            [
                'title' => 'ماوس رپو مدل RAPOO N100',
                'brand' => 'Rapoo',
                'category' => 'ماوس',
                'unit_name' => 'عدد',
                'keywords' => [
                    'ماوس رپو مدل N100',
                    'pars gostar',
                    'پارس گستر',
                    'rapoo n100',
                    'گارانتی: پانا',
                    'فروشگاه انلاین',
                    'خرید انلاین',
                    'فروشگاه',
                    'ماوس رپو مدل RAPOO N100',
                    'گارانتی : پانا',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'پانا',
                    'weight' => 81,
                    'price' => 170000,
                    'stock_count' => 52,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 149900,
                ],
            ],
            [
                'title' => 'سوییچ 5 پورت تی پی لینک مدل TP-LINK LS1005',
                'brand' => 'tp_link',
                'category' => 'سوییچ',
                'unit_name' => 'عدد',
                'keywords' => [
                    'سوییچ 5 پورت تی پی لینک مدل TP-LINK LS1005',
                    'خرید انلاین',
                    'پارس گستر',
                    'فروشگاه انلاین',
                    'pars gsotar',
                    'گارانتی : 36 ماهه پانا',
                    'نمایندگی تی پی لینک',
                    'نمایندگی پانا',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'سفید',
                    'size' => null,
                    'guarantee' => '36 ماه اصلی (پانا-پارس ارتباط-متم اف)',
                    'weight' => 300,
                    'price' => 350000,
                    'stock_count' => 51,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 312490,
                ],
            ],
            [
                'title' => 'خنک کننده پردازنده دیپ کول DEEPCOOL AG200',
                'brand' => 'DEEPCOOL',
                'category' => 'خنک کننده پردازنده',
                'unit_name' => 'عدد',
                'keywords' => [
                    'گارانتی : 18 ماهه نیکان پاسارگاد',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'خنک کننده پردازنده دیپ کول DEEPCOOL AG200',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => '18 ماهه نیکان پاسارگاد',
                    'weight' => 500,
                    'price' => 850000,
                    'stock_count' => 51,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 769900,
                ],
            ],
            [
                'title' => 'اس اس دی اینترنال کینگ مکس مدل KingMax KM256GSIV32 256GB',
                'brand' => 'kingmax',
                'category' => 'حافظه SSD',
                'unit_name' => 'عدد',
                'keywords' => [
                    'pars gostar',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'پارس گستر',
                    'گارانتی : آواژنگ',
                    'اس اس دی اینترنال کینگ مکس مدل KingMax KM256GSIV32 256GB',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'آواژنگ',
                    'weight' => 250,
                    'price' => 1390000,
                    'stock_count' => 50,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 1099000,
                ],
            ],
            [
                'title' => 'کارت شبکه‌ بی‌سیم تندا مدل TENDA W322E',
                'brand' => 'Tenda',
                'category' => 'کارت شبکه',
                'unit_name' => 'عدد',
                'keywords' => [
                    'کارت شبکه‌ ',
                    'کارت شبکه‌ بی‌سیم تندا مدل W322E',
                    'Wireless',
                    'پارس گستر',
                    'فروش انلاین',
                    'کارت شبکه‌ بی‌سیم تندا مدل TENDA W322E',
                    'گارانتی: اصلی(آواژنگ ، آسان پیشرو)',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'نمایندگی تندا',
                    'گارانتی : 36 ماهه آسان پیشرو',
                    'نمایندگی آسان پیشرو',
                    'نمایندگی آواژنگ',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'سبز',
                    'size' => null,
                    'guarantee' => 'اصلی ( آواژنگ ، آسان پیشرو )',
                    'weight' => 30,
                    'price' => 339000,
                    'stock_count' => 50,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 319000,
                ],
            ],
            [
                'title' => 'سوییچ شبکه 5 پورت تندا مدل TENDA S105',
                'brand' => 'Tenda',
                'category' => 'سوییچ',
                'unit_name' => 'عدد',
                'keywords' => [
                    'سوییچ',
                    'Switch',
                    'سوییچ شبکه 5 پورت تندا مدل S105',
                    ' تندا ',
                    'پارس گستر',
                    'فروش انلاین',
                    'Tenda',
                    'خرید ارزان',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'parsgostar',
                    'سوییچ شبکه 5 پورت تندا مدل TENDA S105',
                    'گارانتی : آواژنگ',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'سفید',
                    'size' => null,
                    'guarantee' => 'اصلی ( آواژنگ ، آسان پیشرو )',
                    'weight' => 120,
                    'price' => 288000,
                    'stock_count' => 50,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 234000,
                ],
            ],
            [
                'title' => 'کیبورد و ماوس رپو مدل RAPOO X125S',
                'brand' => 'Rapoo',
                'category' => 'کیبورد',
                'unit_name' => 'عدد',
                'keywords' => [
                    'کیبورد و ماوس رپو',
                    'کیبورد و ماوس رپو مدل RAPOO X125S',
                    'پارس گستر',
                    'PARS GOSTAR',
                    'خرید آنلاین',
                    'فروشگاه آنلاین',
                    'گارانتی : پانا',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'پانا',
                    'weight' => 400,
                    'price' => 565000,
                    'stock_count' => 50,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 519000,
                ],
            ],
            [
                'title' => 'فلش مموری USB 2.0 سن دیسک مدل SanDisk Cruzer Blade CZ50 32GB',
                'brand' => 'sandisk',
                'category' => 'فلش مموری',
                'unit_name' => 'عدد',
                'keywords' => [
                    'فلش مموری USB 2.0 سن دیسک مدل SanDiskCruzer Blade CZ50 32GB',
                    'نمایندگی سازگار',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'نمایندگی سن دیسک',
                    'گارانتی : مادام العمر سازگار',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'مادام العمر سازگار',
                    'weight' => 300,
                    'price' => 237000,
                    'stock_count' => 49,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 177900,
                ],
            ],
            [
                'title' => 'ماوس پد طبی طرح لاجیتک  مدل Logitech PD700',
                'brand' => 'Logitech',
                'category' => 'کیبورد و ماوس پد',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"ماوس پد طبی طرح لاجیتک  مدل Logitech PD 700',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'اصالت و سلامت فیزیکی',
                    'weight' => 300,
                    'price' => 158000,
                    'stock_count' => 49,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 150000,
                ],
            ],
            [
                'title' => 'کابل افزایش طول USB 2.0 انزو ENZO AG1 1.5M',
                'brand' => 'ENZO',
                'category' => 'انواع کابل و مبدل ها',
                'unit_name' => 'عدد',
                'keywords' => [
                    'کابل افزایش طول USB 2.0 انزو ENZO AG1 1.5M',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'نمایندگی انزو سرویس',
                    'نمایندگی انزو',
                    'گارانتی : 60 ماهه انزو سرویس',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'خاکستری',
                    'size' => null,
                    'guarantee' => '60 ماه انزو سرویس',
                    'weight' => 500,
                    'price' => 43900,
                    'stock_count' => 49,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 41900,
                ],
            ],
            [
                'title' => 'اس اس دی اینترنال ادلینک مدل AddLink S20 256GB',
                'brand' => 'addlink',
                'category' => 'حافظه SSD',
                'unit_name' => 'عدد',
                'keywords' => [
                    'اس اس دی',
                    'SSD',
                    'parsgostar',
                    'پارس گستر',
                    'خرید انلاین',
                    'با تخفیف',
                    'اس اس دی اینترنال ادلینک مدل AddLink S20 256GB',
                    'گارانتی : آواژنگ',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'آواژنگ',
                    'weight' => 200,
                    'price' => 1250000,
                    'stock_count' => 49,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 1069000,
                ],
            ],
            [
                'title' => 'سوییچ 5 پورت تندا مدل TENDA SG105',
                'brand' => 'Tenda',
                'category' => 'سوییچ',
                'unit_name' => 'عدد',
                'keywords' => [
                    'سوییچ 5 پورت تندا مدل SG105',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'سوییچ 5 پورت تندا مدل TENDA SG105',
                    'گارانتی : آواژنگ',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'اصلی ( آواژنگ ، آسان پیشرو )',
                    'weight' => 254,
                    'price' => 550000,
                    'stock_count' => 48,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 514000,
                ],
            ],
            [
                'title' => 'اس اس دی ای دیتا مدل ADATA SU650 240GB',
                'brand' => 'ADATA',
                'category' => 'حافظه SSD',
                'unit_name' => 'عدد',
                'keywords' => [
                    'خرید آنلاین',
                    'فروشگاه آنلاین',
                    'پارس گستر',
                    'ای دیتا',
                    'گارانتی : آونگ',
                    'نمایندگی آونگ',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => '36 ماهه آونگ',
                    'weight' => 200,
                    'price' => 1500000,
                    'stock_count' => 47,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 1269000,
                ],
            ],
            [
                'title' => 'ماوس پد طبی طرح ایباکس مدل EBOX PD700',
                'brand' => 'EBOX',
                'category' => 'کیبورد و ماوس پد',
                'unit_name' => 'عدد',
                'keywords' => [
                    'گارانتی : سلامت فیزیکی',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'ماوس پد طبی طرح ایباکس مدل EBOX PD700',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'سلامت فیزیکی',
                    'weight' => 500,
                    'price' => 158000,
                    'stock_count' => 47,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 150000,
                ],
            ],
            [
                'title' => 'کابل شبکه CAT6 بلدن مدل BELDEN 10m',
                'brand' => 'BELDEN',
                'category' => 'کابل شبکه (LAN)',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"کابل شبکه CAT6 بلدن مدل BELDEN 10m',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'تک رنگ',
                    'size' => null,
                    'guarantee' => 'اصالت و سلامت فیزیکی کالا',
                    'weight' => 300,
                    'price' => 73000,
                    'stock_count' => 47,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 66800,
                ],
            ],
            [
                'title' => 'اس اس دی اینترنال کینگ مکس مدل KINGMAX M.2 PQ3480 1TB',
                'brand' => 'kingmax',
                'category' => 'حافظه SSD',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"اس اس دی اینترنال کینگ مکس مدل KINGMAX M.2 PQ3480 1TB',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'آواژنگ',
                    'weight' => 400,
                    'price' => 3430000,
                    'stock_count' => 47,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 3149000,
                ],
            ],
            [
                'title' => 'ماوس پد گیمینگ آئولا AULA MP-WFFM',
                'brand' => 'AULA',
                'category' => 'کیبورد و ماوس پد',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"ماوس پد گیمینگ آئولا AULA MP-WFFM',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'انزو سرویس',
                    'weight' => 500,
                    'price' => 139000,
                    'stock_count' => 46,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 124000,
                ],
            ],
            [
                'title' => 'سوییچ 5 پورت تی پی لینک مدل TP-LINK LS1005G',
                'brand' => 'tp_link',
                'category' => 'سوییچ',
                'unit_name' => 'عدد',
                'keywords' => [
                    'سوییچ 5 پورت تی پی لینک مدل TP-LINK LS1005G',
                    'نمایندگی پانا',
                    'نمایندگی تی پی لینک',
                    'گارانتی : 36 ماهه پانا',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => '36 ماه اصلی (پانا-پارس ارتباط-متم اف)',
                    'weight' => 900,
                    'price' => 650000,
                    'stock_count' => 46,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 569000,
                ],
            ],
            [
                'title' => 'حافظه اس اس دی اینترنال داهوا مدل DAHUA NVMe E900N 256GB',
                'brand' => 'dahua',
                'category' => 'حافظه SSD',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"نمایندگی حامی',
                    'نمایندگی داهوا',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                    'حافظه اس اس دی اینترنال داهوا مدل DAHUA NVMe E900N 256GB',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'حامی',
                    'weight' => 800,
                    'price' => 1250000,
                    'stock_count' => 45,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 1029000,
                ],
            ],
            [
                'title' => 'ماوس پد طبی طرح مایکروسافت مدل Microsoft EF-P4',
                'brand' => 'Microsoft',
                'category' => 'کیبورد و ماوس پد',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"ماوس پد طبی طرح مایکروسافت مدل Microsoft EF-P4',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'اصالت و سلامت فیزیکی',
                    'weight' => 100,
                    'price' => 48900,
                    'stock_count' => 45,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 43500,
                ],
            ],
            [
                'title' => 'منبع تغذیه کامپیوتر کولر مستر مدل COOLER MASTER ELITE 400 V3',
                'brand' => 'Cooler Master',
                'category' => 'منبع تغذیه کامپیوتر',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"منبع تغذیه کامپیوتر کولر مستر مدل COOLER MASTER ELITE 400 V3',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'آواژنگ',
                    'weight' => 500,
                    'price' => 1900000,
                    'stock_count' => 45,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 1799000,
                ],
            ],
            [
                'title' => 'ماوس بی‌سیم رپو مدل RAPOO M160 Silent',
                'brand' => 'Rapoo',
                'category' => 'ماوس',
                'unit_name' => 'عدد',
                'keywords' => [
                    'ماوس بی‌سیم رپو مدل RAPOO M160 Silent',
                    'گارانتی : پانا',
                    'رپو',
                    'پارس گستر',
                    'خرید انلاین',
                    'فروشگاه انلاین',
                    'pars gostar',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'پانا',
                    'weight' => 200,
                    'price' => 415000,
                    'stock_count' => 44,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 364900,
                ],
            ],
            [
                'title' => 'ماوس بی‌سیم رپو مدل RAPOO 1620',
                'brand' => 'Rapoo',
                'category' => 'ماوس',
                'unit_name' => 'عدد',
                'keywords' => [
                    'pars gostar',
                    'پارس گستر',
                    'rapoo1620',
                    'ماوس وایرلس رپو',
                    'ماوس بی‌سیم رپو مدل RAPOO 1620',
                    'گارانتی : پانا',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'پانا',
                    'weight' => 100,
                    'price' => 355000,
                    'stock_count' => 43,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 309900,
                ],
            ],
            [
                'title' => 'فن کیس انزو مدل ENZO FAN-001 RGB',
                'brand' => 'ENZO',
                'category' => 'خنک کننده کیس',
                'unit_name' => 'عدد',
                'keywords' => [
                    '"فن کیس انزو مدل ENZO FAN-001 RGB',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'انزو سرویس',
                    'weight' => 200,
                    'price' => 189000,
                    'stock_count' => 42,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 179000,
                ],
            ],
            [
                'title' => 'هارد اکسترنال سیگیت مدل SEAGATE Expansion 2TB',
                'brand' => 'seagate',
                'category' => 'هارد دیسک اکسترنال',
                'unit_name' => 'عدد',
                'keywords' => [
                    'هارد اکسترنال سیگیت مدل Expansion ظرفیت دو ترابایت',
                    'Expansion ',
                    'هارد اکسترنال سیگیت',
                    'پارس گستر',
                    'pars gostar',
                    'خرید انلاین',
                    'خرید ارزان',
                    'هارد اکسترنال سیگیت مدل SEAGATE Expansion 2TB',
                    'نمایندگی الماس رایان ایرانیان',
                    'نمایندگی سیگیت',
                    ' سازگار',
                    'نمایندگی سازگار',
                    'گارانتی : الماس رایان ایرانیان ، سازگار',
                ],
                'is_available' => 1,
                'is_published' => 1,
                'variants' => [
                    'color_name' => 'مشکی',
                    'size' => null,
                    'guarantee' => 'دو سال سازگار ( 12 ماه بازیابی رایگان اطلاعات)',
                    'weight' => 159,
                    'price' => 4150000,
                    'stock_count' => 41,
                    'is_special' => 0,
                    'is_available' => 1,
                    'is_published' => 1,
                    'discounted_price' => 3799000,
                ],
            ],
        ];

        foreach ($products as $product) {
            $p = Product::create([
                'brand_id' => Brand::query()->where('latin_name', $product['brand'])->first()->id,
                'category_id' => Category::query()->where('name', $product['category'])->first()->id,
                'title' => $product['title'],
                'escaped_title' => NumberConverter::toEnglish($product['title']),
                'slug' => str_slug_persian($product['title']),
                'image_id' => FileManager::query()->where('name', $mappedImages[$product['brand']])->first()->id,
                'description' => '',
                'unit_name' => $product['unit_name'],
                'keywords' => $product['keywords'],
                'is_available' => $product['is_available'],
                'is_published' => $product['is_published'],
                'created_at' => now(),
                'created_by' => 1,
            ]);

            $color = $colors->random();
            ProductProperty::create([
                'product_id' => $p->id,
                'code' => get_nanoid(),
                'color_name' => $color->name,
                'color_hex' => $color->hex,
                'size' => $product['variants']['size'],
                'guarantee' => $product['variants']['guarantee'],
                'weight' => $product['variants']['weight'],
                'price' => $product['variants']['price'],
                'discounted_price' => $product['variants']['discounted_price'] ?? null,
                'tax_rate' => 10,
                'stock_count' => $product['variants']['stock_count'],
                'max_cart_count' => 1,
                'is_special' => $product['variants']['is_special'],
                'is_available' => 1,
                'is_published' => $product['variants']['is_published'],
            ]);
        }
    }
}
