<?php

return [
    'mode' => 'utf-8',
    'format' => 'A4',
    'default_font_size' => '12',
    'default_font' => 'iransans',
    'margin_left' => 7,
    'margin_right' => 7,
    'margin_top' => 7,
    'margin_bottom' => 7,
    'margin_header' => 0,
    'margin_footer' => 0,
    'orientation' => 'P',
    'title' => env('APP_NAME', 'IriaKala'),
    'subject' => '',
    'author' => '',
    'watermark' => '',
    'show_watermark' => true,
    'show_watermark_image' => false,
    'watermark_font' => 'IRANSans',
    'display_mode' => 'fullpage',
    'watermark_text_alpha' => 0.1,
    'watermark_image_path' => '',
    'watermark_image_alpha' => 0.2,
    'watermark_image_size' => 'D',
    'watermark_image_position' => 'P',
    'custom_font_dir' => base_path('resources/css/fonts/'),
    'custom_font_data' => [
        'iransans' => [
            'R' => 'IRANSansWeb.ttf',
            'B' => 'IRANSansWeb_Bold.ttf',
            'useOTL' => 0xFF,
            'useKashida' => 75,
        ]
    ],
    'auto_language_detection' => false,
    'temp_dir' => storage_path('app'),
    'pdfa' => false,
    'pdfaauto' => false,
    'use_active_forms' => false,
];
