<template>
  <partial-general-title
    type="side"
    title="پیشنهاد‌های شگفت‌انگیز"
    title-size="text-xl bg-clip-text text-transparent bg-gradient-to-r from-yellow-500 via-orange-500 to-rose-600"
    container-class="mb-5 mt-6 p-2"
    line-class="bg-gradient-to-r from-yellow-500 via-orange-500 to-rose-600"
  />

  <product-carousel :products="products">
    <template #slide="{slide}">
      <div class="w-full h-full">
        <product-card :product="slide"
                      container-class="rounded-lg shadow-lg border-[3px] border-rose-400"/>
      </div>
    </template>
  </product-carousel>
</template>

<script setup>
import {ref} from "vue";
import PartialGeneralTitle from "@/components/partials/PartialGeneralTitle.vue";
import ProductCarousel from "@/components/product/ProductCarousel.vue";
import ProductCard from "@/components/product/ProductCard.vue";

const products = ref([
  {
    id: 1,
    brand_id: 2,
    category_id: 5,
    title: 'گوشی موبایل سامسونگ مدل Galaxy S23 Ultra دو سیم کارت ظرفیت 256 گیگابایت و رم 12 گیگابایت - ویتنام',
    brand: {
      name: 'سامسونگ',
    },
    category: {
      name: 'موبایل',
    },
    image: {
      name: 'samsung_s23_ultra',
      path: '/src/assets/product/g1.jpg',
    },
    festivals: [
      {
        festival_id: 1,
        product_id: 1,
        discount_percentage: 2,
      },
    ],
    products: [
      {
        id: 1,
        color_name: 'مشکی',
        color_hex: '#000000',
        size: null,
        guarantee: null,
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 8,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
    ],
  },
  {
    id: 2,
    brand_id: 2,
    category_id: 5,
    title: 'گوشی موبایل سامسونگ مدل Galaxy S23 Ultra دو سیم کارت ظرفیت 256 گیگابایت و رم 12 گیگابایت - ویتنام',
    brand: {
      name: 'سامسونگ',
    },
    category: {
      name: 'موبایل',
    },
    image: {
      name: 'samsung_s23_ultra',
      path: '/src/assets/product/g2.jpg',
    },
    festivals: [
      {
        festival_id: 1,
        product_id: 1,
        discount_percentage: 2,
      },
    ],
    products: [
      {
        id: 1,
        color_name: 'مشکی',
        color_hex: '#000000',
        size: 'XL',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 8,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
      {
        id: 2,
        color_name: 'مشکی',
        color_hex: '#000000',
        size: 'XLL',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 10,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: true,
        show_call_for_more: false,
      },
      {
        id: 3,
        color_name: 'کرم',
        color_hex: '#F3ECE2',
        size: 'L',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49700000,
        discounted_price: 48700000,
        stock_count: 5,
        max_cart_count: 3,
        is_available: true,
        is_special: true,
        show_coming_soon: false,
        show_call_for_more: false,
      },
      {
        id: 4,
        color_name: 'بنفش',
        color_hex: '#E7DBE5',
        size: 'L',
        guarantee: 'گارانتی ۲۴ ماهه شرکتی',
        price: 49950000,
        discounted_price: 48950000,
        stock_count: 5,
        max_cart_count: 2,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
    ],
  },
  {
    id: 3,
    brand_id: 2,
    category_id: 5,
    title: 'گوشی موبایل سامسونگ مدل Galaxy S23 Ultra دو سیم کارت ظرفیت 256 گیگابایت و رم 12 گیگابایت - ویتنام',
    brand: {
      name: 'سامسونگ',
    },
    category: {
      name: 'موبایل',
    },
    image: {
      name: 'samsung_s23_ultra',
      path: '/src/assets/product/g3.jpg',
    },
    festivals: [
      {
        festival_id: 1,
        product_id: 1,
        discount_percentage: 2,
      },
    ],
    products: [
      {
        id: 1,
        color_name: 'مشکی',
        color_hex: '#000000',
        size: 'XL',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 8,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
      {
        id: 2,
        color_name: 'مشکی',
        color_hex: '#000000',
        size: 'XLL',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 10,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: true,
        show_call_for_more: false,
      },
      {
        id: 3,
        color_name: 'کرم',
        color_hex: '#F3ECE2',
        size: 'L',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49700000,
        discounted_price: 48700000,
        stock_count: 5,
        max_cart_count: 3,
        is_available: true,
        is_special: true,
        show_coming_soon: false,
        show_call_for_more: false,
      },
      {
        id: 4,
        color_name: 'بنفش',
        color_hex: '#E7DBE5',
        size: 'L',
        guarantee: 'گارانتی ۲۴ ماهه شرکتی',
        price: 49950000,
        discounted_price: 48950000,
        stock_count: 5,
        max_cart_count: 2,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
    ],
  },
  {
    id: 4,
    brand_id: 2,
    category_id: 5,
    title: 'گوشی موبایل سامسونگ مدل Galaxy S23 Ultra دو سیم کارت ظرفیت 256 گیگابایت و رم 12 گیگابایت - ویتنام',
    brand: {
      name: 'سامسونگ',
    },
    category: {
      name: 'موبایل',
    },
    image: {
      name: 'samsung_s23_ultra',
      path: '/src/assets/product/g4.jpg',
    },
    festivals: [
      {
        festival_id: 1,
        product_id: 1,
        discount_percentage: 2,
      },
    ],
    products: [
      {
        id: 1,
        color_name: 'مشکی',
        color_hex: '#000000',
        size: null,
        guarantee: null,
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 8,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
    ],
  },
  {
    id: 5,
    brand_id: 2,
    category_id: 5,
    title: 'گوشی موبایل سامسونگ مدل Galaxy S23 Ultra دو سیم کارت ظرفیت 256 گیگابایت و رم 12 گیگابایت - ویتنام',
    brand: {
      name: 'سامسونگ',
    },
    category: {
      name: 'موبایل',
    },
    image: {
      name: 'samsung_s23_ultra',
      path: '/src/assets/product/g5.jpg',
    },
    festivals: [
      {
        festival_id: 1,
        product_id: 1,
        discount_percentage: 2,
      },
    ],
    products: [
      {
        id: 1,
        color_name: null,
        color_hex: null,
        size: 'XL',
        guarantee: null,
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 8,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: true,
      },
      {
        id: 2,
        color_name: 'مشکی',
        color_hex: '#000000',
        size: 'XLL',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 0,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
      {
        id: 3,
        color_name: 'کرم',
        color_hex: '#F3ECE2',
        size: 'L',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49700000,
        discounted_price: 48700000,
        stock_count: 5,
        max_cart_count: 3,
        is_available: true,
        is_special: true,
        show_coming_soon: false,
        show_call_for_more: false,
      },
      {
        id: 4,
        color_name: 'بنفش',
        color_hex: '#E7DBE5',
        size: 'L',
        guarantee: 'گارانتی ۲۴ ماهه شرکتی',
        price: 49950000,
        discounted_price: 48950000,
        stock_count: 5,
        max_cart_count: 2,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
    ],
  },
  {
    id: 6,
    brand_id: 2,
    category_id: 5,
    title: 'گوشی موبایل سامسونگ مدل Galaxy S23 Ultra دو سیم کارت ظرفیت 256 گیگابایت و رم 12 گیگابایت - ویتنام',
    brand: {
      name: 'سامسونگ',
    },
    category: {
      name: 'موبایل',
    },
    image: {
      name: 'samsung_s23_ultra',
      path: '/src/assets/product/g6.jpg',
    },
    festivals: [
      {
        festival_id: 1,
        product_id: 1,
        discount_percentage: 2,
      },
    ],
    products: [
      {
        id: 1,
        color_name: 'مشکی',
        color_hex: '#000000',
        size: 'XL',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 8,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
      {
        id: 2,
        color_name: 'مشکی',
        color_hex: '#000000',
        size: 'XLL',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49500000,
        discounted_price: 48500000,
        stock_count: 10,
        max_cart_count: 4,
        is_available: true,
        is_special: false,
        show_coming_soon: true,
        show_call_for_more: false,
      },
      {
        id: 3,
        color_name: 'کرم',
        color_hex: '#F3ECE2',
        size: 'L',
        guarantee: 'گارانتی ۱۸ ماهه شرکتی',
        price: 49700000,
        discounted_price: 48700000,
        stock_count: 5,
        max_cart_count: 3,
        is_available: true,
        is_special: true,
        show_coming_soon: false,
        show_call_for_more: false,
      },
      {
        id: 4,
        color_name: 'بنفش',
        color_hex: '#E7DBE5',
        size: 'L',
        guarantee: 'گارانتی ۲۴ ماهه شرکتی',
        price: 49950000,
        discounted_price: 48950000,
        stock_count: 5,
        max_cart_count: 2,
        is_available: true,
        is_special: false,
        show_coming_soon: false,
        show_call_for_more: false,
      },
    ],
  },
])
</script>
